config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
  	resources :comments
  end
  root 'messages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@message = Message.find(params[:message_id])
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id 
		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all.order("created_at ASC")
	end

	def show
		find_message
	end

	def new		
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit		

	end

	def update		
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy		
		@message.destroy
		redirect_to root_path
	end

	private
		def message_params
			params.require(:message).permit(:title, :description)
		end
		def find_message
		@message = Message.find(params[:id])				
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "comment" %>
	<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Message Board", root_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav">
			<li> <%= link_to "Sign Up", new_user_registration_path %> </li>
			<% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
			<% else %>
				<li><%= link_to "Sign In", new_user_session_path %></li>
			<% end %>
		</ul>
		<% if user_signed_in? %>
			<p><%= link_to "New Message", new_message_path, class: "navbar-right navbar-text navbar_link" %></p>
		<% end %>
	</div>
</div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "message title" %>
	<%= f.input :description, label: "write your message here..." %>
	<%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h2>Edit Message</h2>
<%= render 'form' %>

app/views/messages/index.html.erb
<h1>welcome to the message board.</h1>
<% @messages.each do |message| %>
	<h3><%= message.title %></h3>
	<%= link_to "View Message", message_path(message), class: "btn, btn-default" %>
<% end %>
<br><br><br>
<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Messages Here</h1>
<%= render 'form' %>

app/views/messages/show.html.erb
<h3>show file</h3>
<p><%= @message.title %></p>
<br><br>
<p><%= @message.description %></p>
<h3>Comments:</h3>
<%= render @message.comments %>
<h3>Reply:</h3>
<%= render 'comments/form' %>
<br><br>
<%= link_to "home", root_path %>,
<%= link_to "edit", edit_message_path(@message) %>,
<%= link_to "delete", message_path(@message), method: :delete, data: { confirm: "Seriously?" } %>
<br><br><br>